export const SET_USER_NAME = 'SET_USER_NAME'

export const ADD_POKEMON = 'ADD_POKEMON'
export const REMOVE_POKEMON = 'REMOVE_POKEMON'

export const SET_CONTAINER_SCROLL_ELEMENT = 'SET_CONTAINER_SCROLL_ELEMENT'
export const SET_SCROLL_POSITION = 'SET_SCROLL_POSITION'

